from typing import Dict, Any
from app.models.enums import Language

PROMPTS: Dict[Language, Dict[str, str]] = {
    Language.HI: {
        "GREETING": "जनसेतु एआई स्वास्थ्य सेवा में आपका स्वागत है। Welcome to JanSethu AI Healthcare.",
        "PHONE_REGISTRATION_NAME": "नमस्ते, जनसेतु में आपका स्वागत है। आप पहली बार कॉल कर रहे हैं। आपका नाम क्या है?",
        "REGISTRATION_SUCCESS": "नमस्ते {name} जी, जनसेतु पर आपका रजिस्ट्रेशन हो गया है। आप किस भाषा में बात करना चाहेंगे? हिंदी, मराठी या इंग्लिश?",
        "RETURNING_GREETING": "नमस्ते {name} जी! जनसेतु में आपका स्वागत है। आज मैं आपकी क्या सहायता कर सकता हूँ? आप ओपीडी अपॉइंटमेंट बुक कर सकते हैं, अपॉइंटमेंट देख सकते हैं, रद्द कर सकते हैं या चेक-इन कर सकते हैं।",
        "LANGUAGE_SELECTION": "आप किस भाषा में बात करना चाहेंगे? हिंदी, मराठी या इंग्लिश?",
        "MAIN_MENU": "जनसेतु में आपका स्वागत है। आप डॉक्टर अपॉइंटमेंट बुक करने, अपनी स्थिति जांचने, अपॉइंटमेंट बदलने, रद्द करने या आज का ओपीडी टोकन लेने के लिए सीधे बोल सकते हैं।",
        "LOCATION_INPUT": "कृपया अपना 6-अंकों का पिनकोड या क्षेत्र का नाम बताएं, जैसे बारामती।",
        "FACILITY_SELECTION": "उपलब्ध स्वास्थ्य केंद्र:\n{facility_options}\nआप किस अस्पताल में डॉक्टर दिखाना चाहते हैं?",
        "DEPARTMENT_SELECTION": "उपलब्ध ओपीडी विभाग:\n{department_options}\nआप किस विभाग में दिखाना चाहते हैं?",
        "DOCTOR_SELECTION": "उपलब्ध डॉक्टर:\n{doctor_options}\nआप किस डॉक्टर से परामर्श लेना चाहते हैं?",
        "DATE_SELECTION": "आप किस दिन की अपॉइंटमेंट चाहते हैं? आज, कल, या परसों?",
        "SLOT_SELECTION": "उपलब्ध समय स्लॉट:\n{slot_options}\nआप कौन सा समय चुनना पसंद करेंगे?",
        "BOOKING_CONFIRMATION": "मैं डॉ. {doctor_name}, {facility_name}, दिनांक {date}, समय {start_time} - {end_time} की अपॉइंटमेंट बुक कर रहा हूँ। क्या मैं इसे कन्फर्म कर दूँ?",
        "BOOKING_SUCCESS": "बधाई हो! आपकी ओपीडी अपॉइंटमेंट सफलतापूर्वक बुक हो गई है। आपका पुष्टि कोड है: {confirmation_code}। आपके मोबाइल नंबर पर एसएमएस भेज दिया गया है। जनसेतु से जुड़ने के लिए धन्यवाद।",
        "CHECK_APPOINTMENT_PROMPT": "आप अपनी अपॉइंटमेंट की स्थिति जांचना चाहते हैं। आप अपनी हालिया अपॉइंटमेंट के बारे में पूछ सकते हैं।",
        "CHECK_APPOINTMENT_RESULT": "आपकी अपॉइंटमेंट स्थिति: कोड {confirmation_code} — डॉक्टर: {doctor_name}, स्वास्थ्य केंद्र: {facility_name}, तिथि: {date} समय {start_time}। स्थिति: {status}।",
        "CANCEL_APPOINTMENT_PROMPT": "क्या आप अपनी हालिया अपॉइंटमेंट ({confirmation_code}) रद्द करना चाहते हैं?",
        "CANCEL_SUCCESS": "आपकी अपॉइंटमेंट {confirmation_code} सफलतापूर्वक रद्द कर दी गई है। पुष्टि एसएमएस भेजा जा रहा है।",
        "RESCHEDULE_APPOINTMENT_PROMPT": "क्या आप अपनी हालिया अपॉइंटमेंट ({confirmation_code}) का समय बदलना चाहते हैं?",
        "RESCHEDULE_CONFIRMATION": "अपॉइंटमेंट का नया समय: डॉ. {doctor_name}, {facility_name}, दिनांक {date}, समय {start_time} - {end_time}। क्या मैं नया समय कन्फर्म कर दूँ?",
        "RESCHEDULE_SUCCESS": "आपकी अपॉइंटमेंट {confirmation_code} का समय सफलतापूर्वक बदल दिया गया है। नया समय: {date} {start_time}। एसएमएस भेजा जा रहा है।",
        "CHECK_IN_SUCCESS": "आपका चेक-इन सफलतापूर्वक हो गया है। आपका ओपीडी क्यू टोकन है: {queue_token}। कृपया अस्पताल पहुंचने पर प्रतीक्षा क्षेत्र में रहें।",
        "CHECK_IN_FAILED": "चेक-इन करने में असमर्थ: {error_detail}।",
        "NO_CHECKIN_APPOINTMENT": "आज के लिए आपकी कोई कन्फर्म ओपीडी अपॉइंटमेंट नहीं मिली।",
        "NO_APPOINTMENTS": "आपकी कोई सक्रिय अपॉइंटमेंट नहीं मिली।",
        "NO_SLOTS_AVAILABLE": "क्षमा करें, इस तिथि पर कोई स्लॉट उपलब्ध नहीं है। कृपया दूसरी तिथि चुनें।",
        "DEPARTMENT_UNAVAILABLE": "Is department mein abhi appointment available nahi hai. Kripya doosra department chunein ya baad mein prayas karein. 9 dabakar peeche jaayein.",
        "FACILITY_UNAVAILABLE": "Yeh swasthya kendra vartaman mein upalabdh nahi hai. Kripya doosra kendra chunein. 9 dabakar peeche jaayein.",
        "SLOT_TAKEN": "माफी कीजिए, यह स्लॉट अब उपलब्ध नहीं है। कृपया दूसरा स्लॉट चुनें।",
        "EMERGENCY": "🚨 आपातकालीन सूचना: यदि यह एक गंभीर चिकित्सा आपातस्थिति है, तो कृपया तुरंत 108 पर कॉल करें। नजदीकी एम्बुलेंस और अस्पताल सहायता उपलब्ध कराई जा रही है। जनसेतु हेल्पलाइन आपातकालीन मोड एक्टिव है।",
        "HELP": "सहायता: आप अपनी आवश्यकता सीधे बोल सकते हैं, जैसे डॉक्टर बुक करें, अपॉइंटमेंट देखें, या चेक-इन करें।",
        "INVALID_INPUT": "माफ कीजिए, मुझे समझ नहीं आया। क्या आप अपनी बात दोबारा बोल सकते हैं?",
        "ENDED": "जनसेतु एआई का उपयोग करने के लिए धन्यवाद। आपका स्वास्थ्य हमारी प्राथमिकता है। कॉल समाप्त हो गई है।",
    },
    Language.MR: {
        "GREETING": "जनसेतु एआय आरोग्य सेवेत आपले स्वागत आहे. Welcome to JanSethu AI Healthcare.",
        "PHONE_REGISTRATION_NAME": "नमस्कार, जनसेतु मध्ये आपले स्वागत आहे. आपण पहिल्यांदा कॉल करत आहात. आपले नाव काय आहे?",
        "REGISTRATION_SUCCESS": "नमस्कार {name} जी, जनसेतु वर आपले खाते तयार झाले आहे. आपण कोणत्या भाषेत बोलू इच्छिता?",
        "RETURNING_GREETING": "नमस्कार {name} जी. जनसेतु सेवेत आपले स्वागत आहे. आज मी आपली काय मदत करू शकतो? आपण ओपीडी अपॉइंटमेंट बुक करू शकता, स्थिती तपासू शकता किंवा चेक-इन करू शकता.",
        "LANGUAGE_SELECTION": "आपण कोणत्या भाषेत बोलू इच्छिता? हिंदी, मराठी किंवा इंग्लिश?",
        "MAIN_MENU": "जनसेतु मध्ये आपले स्वागत आहे. आपण अपॉइंटमेंट बुक करण्यासाठी, स्थिती तपासण्यासाठी, रद्द करण्यासाठी किंवा चेक-इनसाठी थेट बोलू शकता.",
        "LOCATION_INPUT": "कृपया आपला 6-अंकी पिनकोड किंवा क्षेत्राचे नाव सांगा, जसे बारामती.",
        "FACILITY_SELECTION": "उपलब्ध आरोग्य केंद्र:\n{facility_options}\nआपण कोणत्या रुग्णालयात दाखवू इच्छिता?",
        "DEPARTMENT_SELECTION": "उपलब्ध विभाग:\n{department_options}\nकोणत्या विभागात दाखवायचे आहे?",
        "DOCTOR_SELECTION": "उपलब्ध डॉक्टर:\n{doctor_options}\nकोणत्या डॉक्टरांना भेटायचे आहे?",
        "DATE_SELECTION": "आपण कोणत्या दिवसाची अपॉइंटमेंट इच्छिता? आज, उद्या, की परवा?",
        "SLOT_SELECTION": "उपलब्ध वेळ स्लॉट:\n{slot_options}\nकोणती वेळ सोयीची आहे?",
        "BOOKING_CONFIRMATION": "मी डॉ. {doctor_name}, {facility_name}, तारीख {date}, वेळ {start_time} - {end_time} ची अपॉइंटमेंट बुक करत आहे. मी हे निश्चित करू का?",
        "BOOKING_SUCCESS": "अभिनंदन! आपली ओपीडी अपॉइंटमेंट यशस्वीरित्या बुक झाली आहे. आपला कोड आहे: {confirmation_code}. आपल्या मोबाईलवर एसएमएस पाठवला जात आहे. जनसेतु वापरल्याबद्दल धन्यवाद.",
        "CHECK_APPOINTMENT_PROMPT": "कृपया आपला संदर्भ कोड सांगा किंवा अलीकडील अपॉइंटमेंटबद्दल विचारा.",
        "CHECK_APPOINTMENT_RESULT": "आपली अपॉइंटमेंट स्थिति: {confirmation_code} - डॉक्टर: {doctor_name}, केंद्र: {facility_name}, तारीख: {date} {start_time}. स्थिती: {status}.",
        "CANCEL_APPOINTMENT_PROMPT": "आपण आपली अपॉइंटमेंट ({confirmation_code}) रद्द करू इच्छिता?",
        "CANCEL_SUCCESS": "आपली अपॉइंटमेंट {confirmation_code} यशस्वीरित्या रद्द करण्यात आली आहे. एसएमएस पाठवला जात आहे.",
        "RESCHEDULE_APPOINTMENT_PROMPT": "आपण आपल्या अपॉइंटमेंटची ({confirmation_code}) वेळ बदलू इच्छिता?",
        "RESCHEDULE_CONFIRMATION": "अपॉइंटमेंटची नवीन वेळ: डॉ. {doctor_name}, {facility_name}, तारीख {date}, वेळ {start_time} - {end_time}. मी नवीन वेळ निश्चित करू का?",
        "RESCHEDULE_SUCCESS": "आपल्या अपॉइंटमेंटची {confirmation_code} वेळ यशस्वीरित्या बदलली आहे. नवीन वेळ: {date} {start_time}. एसएमएस पाठवला जात आहे.",
        "CHECK_IN_SUCCESS": "आपले चेक-इन यशस्वीरित्या पूर्ण झाले आहे. आपला ओपीडी क्यू टोकन आहे: {queue_token}. कृपया प्रतीक्षा क्षेत्रात राहा.",
        "CHECK_IN_FAILED": "चेक-इन अयशस्वी: {error_detail}.",
        "NO_CHECKIN_APPOINTMENT": "आजसाठी कोणतीही निश्चित ओपीडी अपॉइंटमेंट सापडली नाही.",
        "NO_APPOINTMENTS": "आपली कोणतीही सक्रिय अपॉइंटमेंट सापडली नाही.",
        "NO_SLOTS_AVAILABLE": "क्षमस्व, या तारखेला कोणताही स्लॉट उपलब्ध नाही. कृपया दुसरी तारीख निवडा.",
        "DEPARTMENT_UNAVAILABLE": "Is department mein abhi appointment available nahi hai. Kripya doosra department chunein ya baad mein prayas karein. 9 dabakar peeche jaayein.",
        "FACILITY_UNAVAILABLE": "Yeh swasthya kendra vartaman mein upalabdh nahi hai. Kripya doosra kendra chunein. 9 dabakar peeche jaayein.",
        "SLOT_TAKEN": "क्षमस्व, हा स्लॉट आता उपलब्ध नाही. कृपया दुसरा स्लॉट निवडा.",
        "EMERGENCY": "🚨 आपत्कालीन सूचना: ही गंभीर वैद्यकीय आणीबाणी असल्यास, कृपया त्वरित 108 वर कॉल करा. जवळची रुग्णवाहिका उपलब्ध केली जात आहे.",
        "HELP": "मदत: आपण थेट बोलून मदत घेऊ शकता, जसे डॉक्टर बुक करा किंवा अपॉइंटमेंट तपासा.",
        "INVALID_INPUT": "क्षमस्व, मला समजले नाही. कृपया पुन्हा सांगा.",
        "ENDED": "जनसेतु एआय वापरल्याबद्दल धन्यवाद. कॉल समाप्त झाला आहे.",
    },
    Language.EN: {
        "GREETING": "Welcome to JanSethu AI Healthcare Platform.",
        "PHONE_REGISTRATION_NAME": "Welcome to JanSethu. You are calling for the first time. What is your name?",
        "REGISTRATION_SUCCESS": "Welcome {name}, your registration is complete. Which language would you prefer?",
        "RETURNING_GREETING": "Welcome back {name} to JanSethu. How can I help you today? You can book an OPD appointment, check status, cancel, or check in.",
        "LANGUAGE_SELECTION": "Which language would you like to speak in? Hindi, Marathi, or English?",
        "MAIN_MENU": "Main Menu: Welcome to JanSethu. You can directly say what you need: book an appointment, check status, cancel, reschedule, or get your queue token.",
        "LOCATION_INPUT": "Please tell me your 6-digit pincode or city name, such as Baramati.",
        "FACILITY_SELECTION": "Available Healthcare Facilities:\n{facility_options}\nWhich facility would you like to visit?",
        "DEPARTMENT_SELECTION": "Select OPD Department:\n{department_options}\nWhich department would you like to visit?",
        "DOCTOR_SELECTION": "Available Doctors:\n{doctor_options}\nWhich doctor would you like to consult?",
        "DATE_SELECTION": "Which day would you like the appointment for? Today, tomorrow, or day after tomorrow?",
        "SLOT_SELECTION": "Available OPD Slots:\n{slot_options}\nWhich time slot works best for you?",
        "BOOKING_CONFIRMATION": "I am booking your appointment with Dr. {doctor_name} at {facility_name} on {date} at {start_time} - {end_time}. Shall I confirm this appointment?",
        "BOOKING_SUCCESS": "Success! Your OPD appointment is booked. Confirmation Code: {confirmation_code}. Confirmation SMS sent. Thank you for using JanSethu AI.",
        "CHECK_APPOINTMENT_PROMPT": "You can ask about your recent appointment or provide your confirmation code.",
        "CHECK_APPOINTMENT_RESULT": "Appointment Status: {confirmation_code} — Dr. {doctor_name} at {facility_name} on {date} at {start_time}. Status: {status}.",
        "CANCEL_APPOINTMENT_PROMPT": "Would you like to cancel your appointment {confirmation_code}?",
        "CANCEL_SUCCESS": "Appointment {confirmation_code} successfully cancelled. SMS notification queued.",
        "RESCHEDULE_APPOINTMENT_PROMPT": "Would you like to reschedule your appointment {confirmation_code}?",
        "RESCHEDULE_CONFIRMATION": "New appointment time: Dr. {doctor_name} at {facility_name} on {date} at {start_time} - {end_time}. Shall I confirm this new time?",
        "RESCHEDULE_SUCCESS": "Appointment {confirmation_code} successfully rescheduled to {date} at {start_time}. Confirmation SMS sent.",
        "CHECK_IN_SUCCESS": "Check-in successful! Your OPD Queue Token is {queue_token}. Please proceed to the waiting area.",
        "CHECK_IN_FAILED": "Check-in failed: {error_detail}.",
        "NO_CHECKIN_APPOINTMENT": "No confirmed appointment found for today.",
        "NO_APPOINTMENTS": "No active appointment found for your phone number.",
        "NO_SLOTS_AVAILABLE": "Sorry, no slots are available for the selected date. Please choose another date.",
        "DEPARTMENT_UNAVAILABLE": "Is department mein abhi appointment available nahi hai. Please select another department or try again later. Press 9 to go back.",
        "FACILITY_UNAVAILABLE": "This facility is currently unavailable for OPD appointments. Press 9 to go back.",
        "SLOT_TAKEN": "Sorry, this slot is no longer available. Please select another slot.",
        "EMERGENCY": "🚨 EMERGENCY NOTICE: For critical medical emergencies, call 108 immediately. Nearest ambulance dispatch notified.",
        "HELP": "Help: You can state your request directly, such as book a doctor, check appointment, or check in.",
        "INVALID_INPUT": "Sorry, I could not understand. Could you please repeat that?",
        "ENDED": "Thank you for calling JanSethu AI Healthcare. Call ended.",
    },
}

class VoicePromptProvider:
    @staticmethod
    def get_prompt(key: str, language: Language = Language.HI, **kwargs: Any) -> str:
        lang_dict = PROMPTS.get(language, PROMPTS[Language.HI])
        template = lang_dict.get(key, PROMPTS[Language.EN].get(key, key))
        try:
            return template.format(**kwargs)
        except Exception:
            return template
